# Generated by Django 6.0.6 on 2026-06-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('request', 'Оставить заявку'), ('discuss', 'Обсудить заказ'), ('availability', 'Уточнить наличие'), ('similar', 'Заказать похожее изделие')], default='request', max_length=20, verbose_name='Тип заявки')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('contact', models.CharField(max_length=150, verbose_name='Контакт для связи')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('personal_data_agreement', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Завершена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_requests', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
